// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbsrfphnaktkaabajswf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtic3JmcGhuYWt0a2FhYmFqc3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTMzNzEsImV4cCI6MjA1OTI2OTM3MX0.FcVauQaLnKQML_D-WFqGauMmKbytMzQOL0ciPyLb0lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);